const middleware = require("../../middleware/client/forgotPassword.middleware")
const validate = require("../../validate/client/validate.userAccount")
const express = require('express')
const route = express.Router()
const controller = require("../../controller/client/forgotPassword.controller")
route.get("/",controller.forgotPassword)
route.post("/",controller.forgotPasswordPost)
route.get("/otp",controller.forgotPasswordOTPinput)
route.post("/otp",controller.forgotPasswordOTPinputPost)
route.get("/resetPassword",middleware.tokenCheck,controller.resetPassword)
route.post("/resetPassword",middleware.tokenCheck,validate.resetPassword,controller.resetPasswordPost)
module.exports = route